---
- name: Docker-compose shortcut
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/local/bin/dc
    state: link

- name: add 'deploy' user to 'docker' group
  user:
    name: deploy
    groups: docker
    append: yes
